name: List Pull Requests

on:
   workflow_dispatch:


jobs:
  list-prs:

    environment: Pythontool

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create Virtual Environment
        run: |
          cd tooltask
          python -m venv venv

      - name: Install Dependencies
        run: |
          cd tooltask

          source venv/bin/activate

          pip install --upgrade pip

          pip install -r requirements.txt

      - name: Run PR Tool
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd tooltask

          source venv/bin/activate

          python main.py \
            --repo ${{ github.repository }} \
            --list-prs
